### ISSUE TITLE
Tracking portfolio through orders 

### ISSUE THREAD

**Issue by PatOConnor43** [anfederico/cryptoview#7]
Hi I've been trying this repo out and it's really nice. Have you thought about looking at the orders on the exchanges to track the portfolio instead of balances? I personally keep ARK in the wallet so I can stake it. Do you see any problems with this? Thanks!

**Comment by anfederico** [comment]
I think this would get messy quickly for most users. One would have to take into account all orders and withdrawals/deposits across every exchange throughout the entire history of an account to predict an accurate balance. And if a user had an exchange that wasn't supported by the app, there would be discrepancies in balances. Overall, I don't think it is a good idea.

**Comment by PatOConnor43** [comment]
I think that the discrepancy that you mentioned is already happening. Without a way to track balances in exchanges as well as individual wallets for each coin you won't be able to have a complete picture. In my opinion, using orders across exchanges gives a more complete information, but I will concede that things like mining or staking still won't be accurately accounted for. Do you have a plan to address the discrepancies when keeping coins off of exchanges?

**Comment by anfederico** [comment]
The discrepancy I was referring to arises in a situation where you buy coins on an unsupported exchange and send them to a supported exchange. A combination of orders, deposits/withdrawals, and balances could work, but for now I don't have plans to incorporate anything more than balances. I think balances serve the purposes of >90% of users.

**Comment by PatOConnor43** [comment]
Okay I'll be keeping an eye on this project. Thanks!
